### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by myroslav321** [t3kit/u16-php7-apache-t3kit#4]
New TYPO3 8.7.9 requires PHP 7.1, current version is 7.0. As a result, when i'm trying to enter 'Extensions' it throws an error
![2017-12-15 14 54 01](https://user-images.githubusercontent.com/20657744/34044228-cffe81f6-e1ac-11e7-8054-ccc775c702ef.png)

**Comment by MattiasNilsson** [comment]
Fixed with this repository: https://github.com/t3kit/ubuntu17.10-php7.1-apache
